Repository hashicorp/hcl-lang, pull requests merged in 2022-10, with the labels that each got.

#137 Update `setup-go` to obtain version via `go-version-file`
  .github/workflows/ci.yml
Labels: technical-debt

#134 Support count and count.index completion in blocks
  decoder/body_candidates.go
  decoder/body_extensions_test.go
  decoder/candidates.go
  decoder/candidates_test.go
  decoder/decoder.go
  decoder/expression_candidates.go
  decoder/hover.go
  decoder/hover_expressions_test.go
  decoder/hover_test.go
  decoder/semantic_tokens.go
  decoder/semantic_tokens_expr_test.go
  decoder/semantic_tokens_test.go
  schema/body_schema.go
  schema/schema.go
Labels: enhancement

#140 Add go.work to gitignore
  .gitignore
Labels: technical-debt

#144 decoder: fix completion & hover for `count` extension value
  decoder/body_candidates.go
  decoder/body_extensions_test.go
  decoder/candidates.go
  decoder/candidates_test.go
  decoder/decoder.go
  decoder/expression_candidates.go
  decoder/hover.go
  decoder/hover_test.go
Labels: bug

#147 Fix bug with DependentBody merging of Extensions
  decoder/body_extensions_test.go
  decoder/decoder.go
Labels: bug
