Repository hashicorp/hcl-lang, pull requests merged in 2023-09, with the labels that each got.

#311 go: Bump version to 1.21
  .go-version
  go.mod
  go.sum
Labels: dependencies

#313 schemahelper: Allow list(any) to be passed into `dynamic` block's `for_each`
  decoder/body_extensions_test.go
  decoder/internal/schemahelper/dynamic_block.go
Labels: bug

#315 go.mod: Fix `go` directive to include patch version
  go.mod
  go.sum
Labels: dependencies

#317 Improve `MinItems` validation for `dynamic` blocks
  decoder/internal/schemahelper/context.go
  decoder/internal/validator/block_max_items.go
  decoder/internal/validator/block_min_items.go
  decoder/internal/walker/walker.go
  decoder/validate_test.go
Labels: bug

#318 decoder: Decouple validators & make them pluggable via PathContext
  decoder/internal/walker/walker.go
  decoder/path_context.go
  decoder/validate.go
  decoder/validate_test.go
  schemacontext/context.go
  validator/attribute_deprecated.go
  validator/attribute_missing_required.go
  validator/attribute_unexpected.go
  validator/block_deprecated.go
  validator/block_labels_length.go
  validator/block_max_items.go
  validator/block_min_items.go
  validator/block_unexpected.go
  validator/validators.go
Labels: enhancement

#320 decoder: Implement completion for binary & unary operators
  decoder/candidates.go
  decoder/expr_any_completion.go
  decoder/expr_any_completion_test.go
  decoder/expr_any_hover.go
  decoder/expr_any_hover_test.go
  decoder/expr_any_ref_origins.go
  decoder/expr_any_ref_origins_test.go
  decoder/expr_any_semtok.go
  decoder/expr_any_semtok_test.go
Labels: enhancement
