Repository hashicorp/hcl-lang, pull requests merged in 2023-11, with the labels that each got.

#338 Skip inferring variable type from default values
  decoder/expression_candidates_legacy_test.go
  decoder/hover_test.go
  decoder/reference_targets.go
  decoder/reference_targets_collect_hcl_test.go
  decoder/reference_targets_collect_json_test.go
  schema/block_schema.go
Labels: bug

#340 Fix type-unaware target collection
  decoder/expr_any_ref_targets.go
  decoder/expr_any_ref_targets_test.go
  decoder/expr_list_ref_targets.go
  decoder/expr_list_ref_targets_test.go
  decoder/expr_literal_type_ref_targets.go
  decoder/expr_literal_type_ref_targets_test.go
  decoder/expr_map_ref_targets.go
  decoder/expr_map_ref_targets_test.go
  decoder/expr_object_ref_targets.go
  decoder/expr_object_ref_targets_test.go
  decoder/expr_set_ref_targets.go
  decoder/expr_tuple_ref_targets.go
  decoder/expr_tuple_ref_targets_test.go
  decoder/reference_targets.go
  decoder/reference_targets_collect_hcl_test.go
  decoder/reference_targets_collect_json_test.go
Labels: bug

#342 github: Disable dependabot for GHA
  .github/dependabot.yml
Labels: dependencies, ci

#344 Improve traversal completion for lists, tuples, and sets
  decoder/expr_list_completion.go
  decoder/expr_list_completion_test.go
  decoder/expr_set_completion.go
  decoder/expr_set_completion_test.go
  decoder/expr_tuple_completion.go
  decoder/expr_tuple_completion_test.go
Labels: bug

#322 decoder: Support template expressions
  decoder/expr_any_completion.go
  decoder/expr_any_completion_test.go
  decoder/expr_any_hover.go
  decoder/expr_any_hover_test.go
  decoder/expr_any_ref_origins.go
  decoder/expr_any_ref_origins_test.go
  decoder/expr_any_semtok.go
  decoder/expr_any_semtok_test.go
  decoder/expr_literal_type_hover.go
  decoder/expr_literal_type_semtok.go
  decoder/reference_origins_collect_hcl_test.go
Labels: enhancement

#326 decoder: Add support for conditional expression
  decoder/expr_any_completion.go
  decoder/expr_any_completion_test.go
  decoder/expr_any_hover.go
  decoder/expr_any_hover_test.go
  decoder/expr_any_ref_origins.go
  decoder/expr_any_ref_origins_test.go
  decoder/expr_any_semtok.go
  decoder/expr_any_semtok_test.go
  decoder/expr_conditional.go
  decoder/expr_literal_type_hover.go
  decoder/expr_literal_type_hover_test.go
  decoder/expr_literal_type_semtok.go
  decoder/semantic_tokens_expr_legacy_test.go
Labels: enhancement
