Repository hashicorp/hcl-lang, pull requests merged in 2023-04, with the labels that each got.

#243 reference: Update type matching to align w/ Terraform's
  decoder/expr_reference_completion_test.go
  decoder/expression_candidates_legacy_test.go
  decoder/hover_expressions_legacy_test.go
  decoder/semantic_tokens_expr_legacy_test.go
  reference/target.go
  reference/targets_test.go
Labels: enhancement

#245 schema: Avoid creating empty `Expr` slice if `Constraint` is set
  schema/attribute_schema.go
Labels: enhancement

#232 decoder: Add support for `AnyExpression` as `Constraint`
  decoder/expr_any.go
  decoder/expr_any_completion.go
  decoder/expr_any_completion_test.go
  decoder/expr_any_hover.go
  decoder/expr_any_hover_test.go
  decoder/expr_any_ref_origins.go
  decoder/expr_any_ref_origins_test.go
  decoder/expr_any_ref_targets.go
  decoder/expr_any_ref_targets_test.go
  decoder/expr_any_semtok.go
  decoder/expr_any_semtok_test.go
  decoder/expr_function.go
  decoder/expr_literal_type_completion.go
  decoder/expr_reference_ref_origins.go
  lang/candidate.go
  lang/candidate_kind_string.go
  lang/semantic_token.go
  reference/traversal.go
  schema/constraint_any_expression.go
  schema/constraint_literal_type.go
Labels: enhancement

#247 Collect implied reference targets for complex types
  decoder/expr_list_ref_targets.go
  decoder/expr_list_ref_targets_test.go
  decoder/expr_literal_type_ref_targets_test.go
  decoder/expr_map_ref_targets.go
  decoder/expr_map_ref_targets_test.go
  decoder/expr_object_ref_targets.go
  decoder/expr_object_ref_targets_test.go
  decoder/expr_set_ref_targets.go
  decoder/expr_set_ref_targets_test.go
  decoder/expr_tuple_ref_targets.go
  decoder/expr_tuple_ref_targets_test.go
  decoder/reference_targets.go
Labels: bug

#253 decoder: Reflect `LiteralValue` `Description` & `IsDeprecated` in completion/hover
  decoder/expr_any_completion_test.go
  decoder/expr_literal_type_completion.go
  decoder/expr_literal_type_completion_test.go
  decoder/expr_literal_value_completion.go
  decoder/expr_literal_value_completion_test.go
  decoder/expr_literal_value_hover.go
  decoder/expr_literal_value_hover_test.go
Labels: bug

#255 fix(schema): crash when completing `LiteralType{Type: cty.Tuple}`
  schema/constraint_literal_type.go
  schema/constraint_literal_type_test.go
Labels: bug

#254 decoder: Display `Tuple` hover data on invalid element
  decoder/expr_tuple_hover.go
  decoder/expr_tuple_hover_test.go
Labels: enhancement

#259 decoder: Fix collection of implied declared targets of complex types
  decoder/expr_list_ref_targets_test.go
  decoder/expr_map_ref_targets_test.go
  decoder/expr_object_ref_targets_test.go
  decoder/expr_set_ref_targets_test.go
  decoder/expr_tuple_ref_targets_test.go
  decoder/reference_targets.go
Labels: bug

#257 decoder: Collect targets w/ interpolation for `Any` correctly
  decoder/expr_any_ref_targets.go
  decoder/expr_any_ref_targets_test.go
Labels: bug

#251 Update legacy tests to use `Constraint`
  decoder/attribute_candidates_legacy_test.go
  decoder/body_candidates_test.go
  decoder/body_extensions_test.go
  decoder/candidates_test.go
  decoder/dependent_body_test.go
  decoder/expr_reference_ref_origins.go
  decoder/expression_candidates_legacy_test.go
  decoder/hover_expressions_legacy_test.go
  decoder/hover_test.go
  decoder/label_candidates_test.go
  decoder/links_test.go
  decoder/reference_origins_collect_hcl_test.go
  decoder/reference_origins_collect_json_test.go
  decoder/reference_targets_collect_extensions_hcl_test.go
  decoder/reference_targets_collect_extensions_json_test.go
  decoder/reference_targets_collect_hcl_test.go
  decoder/reference_targets_collect_json_test.go
  decoder/semantic_tokens_expr_legacy_test.go
  decoder/semantic_tokens_test.go
  decoder/symbols_json_test.go
  schema/attribute_schema_legacy_test.go
  schema/constraint_reference.go
Labels: technical-debt

#250 ci: Add PR test for copyright headers
  .github/workflows/ci.yml
Labels: ci
